production:
  update_event_list:
    class: UpdateEventListJob
    queue: default
    schedule: at 12am every day
  update_event_scores:
    class: UpdateEventScoresJob
    queue: default
    schedule: at 1am every day
